// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0PgqnMxe-V5-gPV0GCvpGPhOQSRWky8E',
    appId: '1:198381499702:web:48581ed3bcf6e242e4ef97',
    messagingSenderId: '198381499702',
    projectId: 'mahavir-70eda',
    authDomain: 'mahavir-70eda.firebaseapp.com',
    storageBucket: 'mahavir-70eda.appspot.com',
    measurementId: 'G-ST1RVJ5Y2V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8PtIR3bgeZXuIDUhDIsqzAZYoQTlh9-o',
    appId: '1:198381499702:android:1b5c6302bbfe6ab5e4ef97',
    messagingSenderId: '198381499702',
    projectId: 'mahavir-70eda',
    storageBucket: 'mahavir-70eda.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0leTcIydg9qKoFMqbjzR8vnXAcf2zxcA',
    appId: '1:198381499702:ios:9b94859c14853ea0e4ef97',
    messagingSenderId: '198381499702',
    projectId: 'mahavir-70eda',
    storageBucket: 'mahavir-70eda.appspot.com',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0PgqnMxe-V5-gPV0GCvpGPhOQSRWky8E',
    appId: '1:198381499702:web:d6ef1733b7deb776e4ef97',
    messagingSenderId: '198381499702',
    projectId: 'mahavir-70eda',
    authDomain: 'mahavir-70eda.firebaseapp.com',
    storageBucket: 'mahavir-70eda.appspot.com',
    measurementId: 'G-8SKYHR715Y',
  );
}
